config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  
  #nested resourses for users/:user_id/portfolios/:portfolio_id/onthemarkets/...
  
  resources :users do
    resource :portfolio do
      resources :onthemarkets
    end
    resources :transactors
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :portfolio
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  #GET request for /users/:id
  def show
    @user = User.find(current_user.id)
    @otm_objs = Onthemarket.where(portfolio_id: @user.id)
  end
  
end

app/views/users/show.html.erb
<div class = "container">
  <div class = "row">
      <div class = "col-lg-12">
        <div class = "col-md-4">
          <%= render '/shared/portfolioCondition' %>
        </div>
        <div class = "col-md-8">
          <div class = "well">
            <!-- A space to chart the value of the current_user's stocks over time -->
            <!-- User should select the stock they wish to view the chart for -->
            <h2 class = "text-center label-callout">Stocks owned by <%= current_user.portfolio.first_name %></h2>
            
            <%# Array of unique stock symbols owned by current user and not ipo %>
            <% array_of_stocks = [] %>
            <% array_of_stocks = Stock.where(portfolio_id: current_user.portfolio.id, ipo: false).pluck(:symbol).uniq %>
            
            <!-- Search database for transactors whose stocks are owned by current user, making sure to limit the return date to just 
            sold_on and price_per. I then store that information as a json hash and use a content tag to send information to js file
            which then plots the chart. -->
            
            <!-- I'd like for the default chart displayed to be the most valuable stock at the time. To determine this, while iterating
            through each of the stocks owned by current user I will save the most valuable one as a variable mvs. When a more valuable stock
            is found the mvs is replaced and the interation continues until all stocks are tested. msv = Most Valuable Stock -->
            <% mvs = nil %>
            <% mvs_value = 0 %>
            <% array_of_stocks.each do |stockSym| %>
              <% id_string = 'transactor_chart_' + stockSym %>
              <!-- Store a hash of the transactors' sold_on and price_per values -->
              <% @trans = Transactor.where(stock_symbol: stockSym) %>
              <% if @trans.count == !nil %>
                <% @trans = @trans.select(:sold_on, :price_per).order(:sold_on) %>
                <% if mvs = !nil %>
                
                
                  <%# if mvs is not nil. Then we need to test whether mvs-value is more than the new price_per. If it is we continue as normal
                  if not mvs-value becomes what ever the price_per value is. %>
                  
                  <% price_test = @trans.last.price_per %>
                  <% if price_test > mvs_value %>
                    <% mvs = stockSym %>
                    <% mvs_value = price_test %>
                  <% end %>
                  
                <% else %>
                  <% mvs = stockSym %>
                  <% mvs_value = @trans.order(:sold_on).last.price_per %>
                <% end %>
              <% end %>
              
              <% @trans.as_json.map(&:symbolize_keys) %>
              <%= content_tag :div, '', id: id_string, data: {transactors: @trans}%>
            <% end %>
            <%# now i have the most valuable stock symbol which is store in mvs %>
            <%= content_tag :div, '', id: 'mvs-string-tag', data: mvs %>
           
           
           
            <!-- Select box whose options are the unique stock symbols owned by current_user -->
            <select id = "select-a-stock">
              <option value="" selected disabled hidden>Select Stock</option>
              <% for i in 0..array_of_stocks.length - 1 %>
                <option><%= array_of_stocks[i] %></option>
              <% end %>
            </select>
      
            <!-- Output chart here. Morris js requires the height parameter to be included -->
            <div id = 'chart-output' style="height: 250px;"></div>
    
          </div>
          
          
          <!-- Sell and Purchase stock from the market -->
          <div class = "well">
            <h2 class = "text-center label-callout">Sell & Purchase Stock</h2>
            <br/>
            
            <%# links to sell and purchase stock %>
            <% if current_user.portfolio.stocks.length != 0 %>
              <div class = "container">
                <div class = "row">
                  <div class = "col-md-5 offset-md-2">
                    <%= link_to "Sell stocks from your portfolio", new_user_portfolio_onthemarket_path(buying: false, user_id: params[:id]), class: 'btn btn-success btn-lg' %></h4>
                  </div>
                  <div class = "col-md-2 ">
                    <%= link_to "Market place search", '#', class: 'btn btn-primary btn-lg ', style: 'float:right;' %>
                  </div>
                </div>
              </div>
            <% else %>
              <%= link_to "Market place search", '#', class: 'btn btn-primary btn-lg ', style: 'float:right;' %>
            <% end %>
            <br/>
            
            
          </div>
          
          
            <div class = "well">
              <h2 class = "text-center label-callout" >Current Listings</h2>
              <% if @otm_objs.any? %>
                <% @otm_objs.each do |otm| %>
                  <h4><%= otm.ideal_number_sold %> x <%= otm.stocks_on_market %> Stock</h4>
                  <p>Price per stock: <%= otm.price_per %></p>
                  <p>Listing active since: <%= otm.updated_at.to_date %></p>
                  <%= link_to 'Remove Listing', user_portfolio_onthemarket_path(user_id: current_user.id, id: otm.id), 
                    :confirm => "Are you sure?", :method => :delete %>
              <% end %>
              <% else %>
                <h4 class = 'text-center'>You have no active listings at this time!</h4>
                <p class = 'text-center'><%= link_to 'Create a listing.', new_user_portfolio_onthemarket_path(buying: false, user_id: params[:id]) %></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>