config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  
  #nested resourses for users/:user_id/portfolios/:portfolio_id/onthemarkets/...
  
  resources :users do
    resource :portfolio do
      resources :onthemarkets
    end
    resources :transactors
  end

end

app/views/shared/_ipos.html.erb
<li class= "container-fluid" style = "list-style:none;">
  
  <% stk = Stock.find_by(symbol: ipo.stocks_on_market) %>
  <h4><b><%= stk.stock_name %></b></h4>
  <p class = "ipoTable">Symbol: <%= ipo.stocks_on_market %><br/>
  Price per stock: <%= sprintf('%.2f', ipo.price_per) %><br/>
  First public offering: <%= ipo.created_at.strftime('%d %b %Y') %></p>

</li>

app/views/shared/_portfolioCondition.html.erb
<h2 class = "text-center portfolio-page-name-callout"> <%= current_user.portfolio.first_name %>'s Portfolio </h2>
<% current_user.portfolio.calc_net_worth() %>
<h5>Net Worth:<span class= "portfolio-page-details">
  <%= sprintf( "%0.02f",current_user.portfolio.net_worth) %>
  </span>
  </h5>
<h5>Balance:<span class = "portfolio-page-details"><%= sprintf( "%0.02f",current_user.portfolio.balance) %></span></h5>
<h5>Total Stocks:<span class = "portfolio-page-details"><%= current_user.portfolio.stocks.length %></span></h5>
<h5>Highest Valued Stock</h5>
<div class = "well on-the-rise">
  <h4>On the rise will be here</h4>
</div>

app/views/shared/_shieldStock.html.erb
<!-- Shield Stock items, when calling to render this, The programmer can specify the objects to draw for
For example passing in Onthemarket.find(1) as one object-->
<div class = "well row">
  <div class = "col-sm-4 text-center">
    <!-- Shield logo with stock information inside -->
    
    <div id="shield">
      yadadyada yada ydad
      here is more place holder text
      filling out the shapes
      lets keep going...
      almost there...
      ok
      <div id = "shield-text">
        <!-- the symbol of the stocks being sold (som) is used to search database for these stocks -->
        <% som = otm1.stocks_on_market %>
        <br/>
        <% stock = Stock.find_by(symbol: som) %>
        <p><%= stock.stock_name %>
        Here is some additonal text to filll the shapes' tex box</p>
        <% if stock.being_id == 2 %>
          <!-- Iterating through each league a club can be part of -->
          <% for i in 0..Club.find_by(name: stock.stock_name).leagues.length - 1 %>
            <p><%= Club.find_by(name: stock.stock_name).leagues[i].name %></p>
          <% end %>
        <% else %>
          <!-- Here will be how i access the leagues if the stock isn't a club-->
        <% end %>
      </div>
    </div>
  </div>
  <div>
    <!-- main information describing the onthemarket object which could be bought -->
    <h2><%= otm1.ideal_number_sold %> x <%= stock.stock_name %> Stock</h2>
    <div class = "col-sm-3">
      <p>Stock Name: <%= stock.stock_name %></p>
      <p>Stock Type: <%= Being.find(stock.being_id).family %></p>
      <p>Stock Symbol: <%= stock.symbol %></p>
    </div>
    <div class = "col-sm-5">
      <p>Price Per Stock: $<%= sprintf('%.2f', otm1.price_per) %></p>
      <p>Minimum purchase quantity: <%= otm1.least_possible %></p>
      <!-- A 'Purchase Now' link is created if the current user does not own the onthemarket object and the current page is the 
      marketplace page -->
      <% if otm1.portfolio_id != current_user.portfolio.id && request.path_info == user_portfolio_onthemarkets_path(user_id: current_user.id) %>
        <p><%= link_to 'Purchase Now', new_user_transactor_path(user_id: current_user.id, onthemarket: otm1.id) %></p>
      <% elsif otm1.portfolio_id = current_user.portfolio.id && request.path_info == user_portfolio_onthemarkets_path(user_id: current_user.id)%>
        
      <% end %>
    </div>
  </div>
</div>
<br/>

app/views/shared/_trending.html.erb
<li class= "container-fluid" style = "list-style:none;">
  
  <% if trn.stock_symbol && trn.stock_symbol != 'TEST' %>
    <% stk = Stock.find_by(symbol: trn.stock_symbol) %>
    <h4><b><%= stk.stock_name %></b></h4>
    <p class = "ipoTable">Symbol: <%= stk.symbol %><br/>
    Price per stock: <%= sprintf('%.2f', trn.price_per) %><br/>
  <% end %>


</li>