config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  
  #nested resourses for users/:user_id/portfolios/:portfolio_id/onthemarkets/...
  
  resources :users do
    resource :portfolio do
      resources :onthemarkets
    end
    resources :transactors
  end

end

app/views/pages/home.html.erb
<div class = "container-fluid">
  <%# backgorouund studium picture with foreground as the shield things %>
  <div class = "row">
    <div class = "col-lg-12 text-center background-color-home home-image-resizing">
       <%= image_tag('stadium_flood_lights.PNG') %>
    </div>
  </div>
</div>



<% if user_signed_in? %>
  <%# Confirmation that user is signed in and if their portfolio has been created yet. %>
  <% if current_user.portfolio %>
    <div class = "container">
      <div class= "row">
        <div class= "col-lg-4">
          <h2>Welcome Back <%= current_user.portfolio.first_name %>!</h2>
        </div>
      </div>
    </div>
    <%# If a user is logged in, they need a link to view their portfolio, and a link to build their portfolio %>
    <%= link_to 'View Your Portfolio', user_path(current_user.id) %>
    <br/>
    <%= link_to 'Edit Your Portfolio Information', edit_user_portfolio_path(user_id: current_user.id) %>
    
    
  <% else %>
  <%# Encourage the new user to fillout their portfolio info before proceeding %>
    <div class = "container">
      <div class = "row" >
        <div class = "col-lg-8 col-lg-offset-3">
          <div class ="col-md-2">
            <i class='fas fa-futbol homepage-portfolio-create'></i>
          </div>
          <div class = "col-md-8">
            <h1>Welcome to Football Marketplace!</h1>
            <p>To get started, please fillout your <%= link_to 'portfolio information here.', new_user_portfolio_path(user_id: current_user.id) %> </p>
          </div>
        </div>
      </div>
    </div>
 
  <% end %>
  
  
<% else %>
  <%# Log in and sign up links if user is not signed in. %>
  <div class = "container">
    <div class = "row" >
      <div class = "col-lg-8 col-lg-offset-3">
        <div class ="col-md-2">
          <i class='fas fa-futbol homepage-signup-ad'></i>
        </div>
        <div class = "col-md-8">
          <h1>Football Marketplace</h1>
          <p>Sign up for free today and recieve $1000 in free in-game currency to build your portfolio!</p>
        </div>
      </div>
    </div>
    <br/>
    
    <div class="row">
      <div class = "col-lg-8 col-lg-offset-2">
        <div class="col-lg-4 col-lg-offset-2 text-center">
          <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary btn-lg btn-block' %>
          <p class = 'text-center'>Log in with your existing Football Marketplace account</p>
        </div>
        <div class="col-lg-4 text-center">
          <%= link_to 'Sign Up', new_user_registration_path , class: 'btn btn-success btn-lg btn-block'%>
          <p class = 'text-center'>Create your own Football Marketplace account</p>
        </div>
      </div>
    </div>
    
    
    
        
        
  </div>
<% end %>


<%# Regardless if a user is currently logged in, we render the IPO, trending stocks and help/info categories below %>
<div class = 'container'>
  <div class = 'row'>
    <div class ="col-md-5 well">
      <h2 class = "text-center label-callout">IPOs</h2>
      <%# Take the five latest ipos to be created %>
      
      <% ipos = Onthemarket.where(ipo: true).order(:created_at).take(5) %>
      <ul>
        <% ipos.each do |stk|%>
          <div class = "container">
            <%# render a list containing these stocks %>
            <%= render '/shared/ipos', :ipo => stk %> 
          </div>
        <% end %>
      </ul>
    </div>
    <div class ="col-md-5 col-md-offset-2 well">
      <h2 class = "text-center label-callout">Trending Stocks</h2>
      <ul>
        <% trends = Transactor.order(:sold_on).take(5) %>
        <% trends.each do |trn| %>
          <div class = "container">
            <%# render a list of trending stocks(for now recently traded) %>
            <%= render '/shared/trending', :trn => trn %>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>


<br/>
<div class = "container">
  <div class = "row">
    <div class ="col-lg-10 col-lg-offset-1">
      <p><h4>What is Football Marketplace?</h4>Football Marketplace is a place to buy, sell and trade fake stock in your favorite european football clubs, players and managers. Trades of stocks are entirely dependent on the users playing the game thus creating a free market. This means sustained success of teams, players, and even managers drives trading prices up while extended periods of real world loss and poor performance drives prices down. The money traded throughout the game is entirely fictional and does not represent real world currency of any kind.</h4>
      </p>
    </div>
  </div>
</div>
<br/>