config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  
  #nested resourses for users/:user_id/portfolios/:portfolio_id/onthemarkets/...
  
  resources :users do
    resource :portfolio do
      resources :onthemarkets
    end
    resources :transactors
  end

end

app/views/layouts/_alerts.html.erb
<p class = "notice"><%= notice %></p>
<p class = "alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Football Marketplace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!-- Meta tag for page specific javascript (psj) -->
    <%= tag :meta, name: :psj, id: 'psj', action: action_name, controller: controller_name %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'rails.validations' %>
  </head>

  <body>
    
    <!-- Navigation bar -->
    <nav class="navbar navbar-default navbar-static-top  header-style" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to '/', class: "navbar-brand" do %>
            <div id = "site-name-navbar">
              <font color = "#000000">
                <i class ='fas fa-futbol'></i>
                Football Marketplace
              </font>
            </div>
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" %>
            <% else %>
              <%= link_to "Log In", new_user_session_path, class: "btn btn-default navbar-btn" %>
              <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default navbar-btn" %>
            <% end %>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <% if current_user.portfolio %>
                <li><%= link_to "Your Portfolio", user_path(id: current_user.id) %></li>
                <li><%= link_to "Market", user_portfolio_onthemarkets_path(user_id: current_user.id) %></li>
              <% else %>
                <li><%= link_to 'Build Portfolio', new_user_portfolio_path(user_id: current_user.id) %></li>
              <% end %>
            <% end %>
            <li><%= link_to "About", '/about' %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    <!-- End of navigation bar -->
    
    <!-- Ticker Tape -->
    <div class = "container-fluid ticker-tape">
      <%# collect the stock symbols and limit to 3 results %>
      <% array_of_symbols = []%>
      <% array_of_symbols = Transactor.pluck(:stock_symbol).uniq %>
      <marquee behavior="scroll" direction="left">
      <% array_of_symbols.each do |sym| %>
        <% search_result = Transactor.where(stock_symbol: sym).order(:sold_on).take(2) %>
        <% if search_result.length == 2 %>
          <%# successfully found at least two objects satisfying search criteria %>
          <%# calculate the change in price between last two Transactors of this type %>
          <% price_change = search_result.last.price_per - search_result.first.price_per %>
          <font color=  "black"><%= Stock.find_by(symbol: sym).stock_name %> (<%= search_result.first.stock_symbol %>)
            : <%= sprintf('%.2f', search_result.last.price_per) %>, </font>
          <% if price_change < 0 %>
            <font color= "red"><%= sprintf('%.2f', price_change) %></font>
          <% elsif price_change > 0 %>
            <font color= "green">+<%= sprintf('%.2f', price_change) %></font>
          <% elsif %>
            +<% sprintf('%.2f', price_change) %>
          <% end %>
          
        <% else %>
          <%# stock has either only one Transactor or none-- so we should skip trying to find a change %>
          
        <% end %>
        <font color = "black">&nbsp;&nbsp;</font>
      <% end %>
      </marquee>
        
    </div>

    <%= render 'layouts/alerts' %>
    <%= yield %>
    
    
    <!-- Footer -->
    <footer class = 'footer text-center'>
      <div class = 'container'>
        <%= link_to "/", class: "footer-brand" do %>
          Football Marketplace 
        <% end %>
        |
        <%= link_to "#" do %>
          FAQ
        <% end %>
        |
        <%= link_to "https://vast-inlet-29334.herokuapp.com/" do %>          
          Developer's Site
        <% end %>
      </div>
    </footer>
    <!-- End of Footer -->
    
  </body>
</html>